Updated html and css to become responsive from mobile to desktop
Shuhad786/Portfolio-setup-and-mobile-version-skeleton pull request #4
Opened 2022-06-01 19:38 UTC by Shuhad786

I had left out certain images as the vectors would not resize.

2022-06-01 20:46 UTC, Ismailco requested changes
### Hi @Shuhad786,
Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
>          <header class="top">
- [ ] Please stick to the Figma design, the nav items should be aligned horizontally in one line

|Your design|Figma design|
|-|-|
|![Screenshot_20220601_211044](https://user-images.githubusercontent.com/25227022/171493618-32c8a1cc-d95c-42d8-9f48-72934af77c43.png)|![Screenshot_20220601_211254](https://user-images.githubusercontent.com/25227022/171493653-6d463e53-4024-4564-938e-3ea40d1d337c.png)|

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
> +            </div>
- [ ] Please consider adding Work and arrows to your design so it's almost like the provided one

|Your design|Figma design|
|-|-|
|![Screenshot_20220601_211103](https://user-images.githubusercontent.com/25227022/171495168-a60ee4b4-146f-48d0-bbac-f7ae9a4dee81.png)|![Screenshot_20220601_211237](https://user-images.githubusercontent.com/25227022/171495207-60d835b3-6dc9-439a-b0bb-39e2217c0825.png)|

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
> +        <form class="form-info" action="https://formspree.io/f/mzbooyno" method="post">
- [ ] You can consider reducing the box shadow and adding more padding to the text area so your design is similar to the Figma design

|Your design|Figma design|
|-|-|
|![Screenshot_20220601_211154](https://user-images.githubusercontent.com/25227022/171496331-b77e8516-9c65-4e41-9f0b-e7b5747b4a3b.png)|![Screenshot_20220601_211213](https://user-images.githubusercontent.com/25227022/171496345-8983dbd3-bf0e-4579-a08b-a55a682139c7.png)|

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
> +                                    <!-- end of desktop version html -->
- [ ] For best practices, please consider using CSS to style the page instead of re-creating the HTML code for mobile

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
> +    <!-- /*Mobile version*/ -->
- [ ] The desktop view is displaying on top of the mobile page in mobile view, kindly consider fixing this

![Screenshot_20220601_213800](https://user-images.githubusercontent.com/25227022/171497488-ca558672-4594-4a40-93db-f4c8383ed541.png)

2022-06-01 20:46 UTC, Ismailco commented on Portfolio mobile.html
>                  <textarea name="messagebox" placeholder="Enter text here" rows="10" cols="30" required maxlength="500"></textarea>
- [ ] Kindly stick to the Figma design, you can add some padding/margin at the bottom of the footer links, and add the email address
- [ ] Kindly remove or reduce the box shadow in the form, so your design is as close to the Figma design as possible

|Your design|Figma design|
|-|-|
|![Screenshot_20220601_214519](https://user-images.githubusercontent.com/25227022/171498272-7712f16c-5dcb-49c3-b624-9d43c14ad169.png)|![Screenshot_20220601_213940](https://user-images.githubusercontent.com/25227022/171498128-2e7f4042-2cc6-425e-b8c8-c6fda4843cc4.png)|

2022-06-03 21:12 UTC, OmarRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @Shuhad786 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 21:14 UTC, merged